---
- name: Install httpd
  ansible.builtin.dnf:
    name: "{{ apache_package }}"
    state: present

- name: Ensure httpd is up and running
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started
    enabled: true

- name: Copy index.html to relevant directory
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: apache
    group: apache
    mode: '0644'
